### ISSUE TITLE
Feature request: ability to add prompt line above current prompt line

### ISSUE THREAD

**Issue by drorspei** [idlespork/idlespork#13]
Sometimes when starting to write a line I remember I didn't initialize a variable properly. The usual solution is to cut what I wrote until now, quickly set the variable, paste back, then continue as normal.

In Jupyter I can just make a new cell above current one and import collections. This means I keep my eyes on the code that's important to me right now.

I purpose to add such a feature to idlespork: if I click ctrl+b or use a new right click menu option, a prompt line is added just above the current prompt and the cursor is moved there. After writing something and submitting for evaluation the cursor will move back to where it was before.

**Comment by ofir-reich** [comment]
My trick is instead of cutting and pasting, to use Ctrl+C (without selection - keyboard interrupt), which doesn't execute the commands but leaves them written there. Then I execute whatever I want, and then use Alt+p (or Ctrl+Up) to get my previous commands back. It also works with a few lines of commands.
Another option, since idlespork let's you write multiple lines before executing, is to go to the start of the lines you're writing now and start writing the code you would need, pressing alt+enter to start a new line without executing, pushing all your written code down. This will execute all together, so not equivalent to a new cell above. I use the former method and it works well for me.

**Comment by drorspei** [comment]
Yeah, that works for me too, thanks :)
